spring.application.name=mydoctor

#Connessione al db
spring.datasource.url=jdbc:postgresql://localhost:5432/my-doctor
spring.datasource.username=postgres
spring.datasource.password=postgres

#Crea automaticamente le tabelle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Utilizzo di PostgrSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.main.banner-mode=off
logging.level.root=warn
łogging.level.org.hibernate.orm.jdbc